#pragma once

#include <pntos/aspn.h>
#include <pntos/plugins/common.h>
#include <pntos/stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

PNTOS_ASSUME_NONNULL_BEGIN

/**
 * An enumeration that specifies frame.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef enum PntosInertialFrame {

	/**
	 * Force vectors in this frame are north-east-down in m/s^2.
	 *
	 * Rotation rate vectors in this frame are of an inertial sensor with respect to inertial frame,
	 * in the inertial sensor frame (rad/s). Sometimes represented as w_s_is (or w_b_ib if the body
	 * frame is aligned with the inertial sensor frame.
	 */
	PNTOS_INERTIAL_FRAME_NED

} PntosInertialFrame;

/**
 * A struct containing specific forces and rotation rates from the inertial.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef struct PntosInertialForcesRates {

	PntosManagedMemory* memory;

	/**
	 * An ASPN IMU message which has been repurposed to hold specific forces (the meas_accel field)
	 * and rotation rates (the meas_gyro field) in a different frame (see #frame).
	 */
	AspnMeasurementImu* forces_and_rates;

	/**
	 * Specifies the frame of the above forces and rates.
	 */
	PntosInertialFrame frame;

} PntosInertialForcesRates;

/**
 * A structure representing the biases on a set of 3-axis gyros and 3-axis accelerometers.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef struct PntosStandardInertialErrors {

	PntosManagedMemory* memory;

	/**
	 * A set of 3 biases for a 3-axis accelerometer in the sensor's (X-Y-Z) frame, expressed in
	 * m/s^2.
	 */
	double accel_biases[3];

	/**
	 * A set of 3 biases for a 3-axis gyro in the sensor's (X-Y-Z) frame, expressed in rad/s.
	 */
	double gyro_biases[3];

	/**
	 * A set of 3 scale factor errors for a 3-axis accelerometer in the sensor's (X-Y-Z) frame,
	 * unitless.
	 */
	double accel_scale_factors[3];

	/**
	 * A set of 3 scale factor errors for a 3-axis gyroscope in the sensor's (X-Y-Z) frame,
	 * unitless.
	 */
	double gyro_scale_factors[3];

	/* TODO: more terms? Possibly sensor misalignment angles?*/
} PntosStandardInertialErrors;

/**
 * An enumeration that allows the user to decide if the solution they request is the best available
 * solution or one that has no discontinuities in it due to resets.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef enum PntosInertialSolutionRangeType {
	PNTOS_INERTIAL_BEST_KNOWN_SOLUTION,
	PNTOS_INERTIAL_NO_UPDATES_WITHIN_RANGE
} PntosInertialSolutionRangeType;

/**
 * An enumeration that allows the user to know which inertial model they are implementing or have.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef enum PntosInertialType {

	/**
	 * A mechanization which involves exactly three orthogonal gyros and three orthogonal
	 * accelerometers that are aligned with each other (accelerometers with gyros). In this
	 * mechanization, the sensor frame is by definition the coordinate frame of the gyros and
	 * accelerometers. Corresponds to an instance of PntosStandardInertialMechanization.
	 */
	PNTOS_STANDARD_INERTIAL_MECHANIZATION,

	/**
	 * A model for an inertial where the solutions are generated by an external source. In this
	 * model, the plugin has less control over the solutions and doesn't mechanize IMU measurements
	 * to produce new solutions. Instead, inertial solutions are stored and buffered so that they
	 * can be interpolated to queried times. It is still possible to approximate inertial forces and
	 * rates with this model but since the solutions are externally generated, it will not generally
	 * be possible to get or set inertial errors or to reset the inertial solutions. Corresponds to
	 * an instance of PntosExternalInertial.
	 */
	PNTOS_EXTERNAL_INERTIAL,

	/**
	 * A mechanization in which either the gyros are not aligned with the accelerometers, or in
	 * which there are three or more gyros that are not orthogonal and/or three or more
	 * accelerometers which are not orthogonal. Corresponds to an (unimplemented) instance of
	 * PntosNonOrthogonalInertialMechanization.
	 */
	PNTOS_NON_ORTHOGONAL_INERTIAL_MECHANIZATION

} PntosInertialType;

/**
 * A common base type for an inertial. A user may use the PntosCommonInertial.mechanization_type
 * field to discover what type of inertial this type actually is and then downcast to the
 * appropriate inertial class. For example, if PntosCommonInertial.mechanization_type is
 * `PNTOS_STANDARD_INERTIAL_MECHANIZATION`, then this instance is actually a
 * PntosStandardInertialMechanization.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef struct PntosCommonInertial {

	PntosManagedMemory* memory;

	/**
	 * The type of this inertial. Used to downcast to the appropriate child class.
	 */
	PntosInertialType inertial_type;

	/**
	 * @return The message type that will be returned by #request_current_solution,
	 * #request_solution, and #request_solutions.
	 */
	PntosMessageType (*request_solution_message_type)(struct PntosCommonInertial* self);

	/**
	 * @return The current inertial solution.
	 */
	PntosMessage* (*request_current_solution)(struct PntosCommonInertial* self);

	/**
	 * @param time The time at which the returned solution should be valid.
	 *
	 * @return The solution computed by this inertial at \p time if \p time is in the valid range,
	 * NULL otherwise (#is_time_in_range can be used to check \p time before calling this method).
	 */
	PntosMessage* PNTOS_NULLABLE (*request_solution)(struct PntosCommonInertial* self,
	                                                 AspnTypeTimestamp time);

	/**
	 * Request a set of solutions computed by this inertial at the given times.
	 *
	 * @param times An array of times at which solutions are requested.
	 * @param num_times The length of \p times.
	 * @param type The type of solution requested.
	 *
	 * @return An array of solutions. Returns NULL if \p type is unsupported by this inertial or
	 * every instance of \p times is outside the valid range. Otherwise guaranteed to not be NULL.
	 */
	PntosMessageArray* PNTOS_NULLABLE (*request_solutions)(struct PntosCommonInertial* self,
	                                                       AspnTypeTimestamp* times,
	                                                       size_t num_times,
	                                                       PntosInertialSolutionRangeType type);

	/**
	 * @param time The query time.
	 *
	 * @return true if a solution exists at \p time, false otherwise. This result is only valid
	 * until another method (for example, process_pntos_message) is called.
	 */
	bool (*is_time_in_range)(struct PntosCommonInertial* self, AspnTypeTimestamp time);

	/**
	 * @return The earliest available time at which a solution or forces and rates can be requested.
	 * This result is only valid until another method (for example, process_pntos_message) is
	 * called.
	 */
	AspnTypeTimestamp (*request_earliest_time)(struct PntosCommonInertial* self);

	/**
	 * @return The latest time at which a solution or forces and rates can be requested. This result
	 * is only valid until another method (for example, process_pntos_message) is called.
	 */
	AspnTypeTimestamp (*request_latest_time)(struct PntosCommonInertial* self);

	/**
	 * @return An array of message types that are supported by this plugin as inputs to
	 * #process_pntos_message.
	 */
	PntosMessageTypeArray* (*request_process_pntos_message_types)(struct PntosCommonInertial* self);

	/**
	 * @param message A new message to be incorporated into the computed inertial solution.
	 */
	void (*process_pntos_message)(struct PntosCommonInertial* self, PntosMessage* message);

	/**
	 * @param time The time at which the forces and rates should be valid.
	 *
	 * @return The instantaneous forces and rates at \p time if \p time is in the valid range, NULL
	 * otherwise (#is_time_in_range can be used to check \p time before calling this method).
	 */
	PntosInertialForcesRates* PNTOS_NULLABLE (*request_forces_and_rates)(
	    struct PntosCommonInertial* self, AspnTypeTimestamp time);

	/**
	 * @param time1 The start of the time range over which the forces and rates should be valid.
	 * @param time2 The end of the time range over which the forces and rates should be valid.
	 *
	 * @return The average forces and rates over the period of time defined by \p time1 and \p time2
	 * if at least one of them is in the valid range, NULL otherwise (#is_time_in_range can be used
	 * to check both times before calling this method).
	 */
	PntosInertialForcesRates* PNTOS_NULLABLE (*request_average_forces_and_rates)(
	    struct PntosCommonInertial* self, AspnTypeTimestamp time1, AspnTypeTimestamp time2);

} PntosCommonInertial;

/**
 * An externally-mechanized inertial.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef PntosCommonInertial PntosExternalInertial;

/**
 * An struct produced by a PntosInertialPlugin that generates solutions from raw IMU data.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef struct PntosStandardInertialMechanization {

	PntosCommonInertial common;

	/**
	 * @return An array of message types that are supported by this plugin for resetting the
	 * inertial solution, or NULL if resetting the inertial solution is an unsupported operation by
	 * the inertial plugin.
	 */
	PntosMessageTypeArray* PNTOS_NULLABLE (*request_reset_message_types)(
	    struct PntosStandardInertialMechanization* self);

	/**
	 * Sets the solution to the values in \p message. For example, if \p message is PVA then the
	 * inertial solution will be set to that PVA. If \p message is just position, then only the
	 * position portion of the inertial solution will be set using \p message.
	 *
	 * @param message A message containing the information necessary to reset the solution. To see
	 * the types supported by the implementation, call #request_reset_message_types().
	 */
	void (*reset_solution)(struct PntosStandardInertialMechanization* self, PntosMessage* message);

	/**
	 * Reset the current inertial internal bias values with corrections from an external source,
	 * such as a filter or error estimator. The errors passed in here will be adjusted for
	 * internally by the inertial when processing incoming data. Thus, if errors are passed into the
	 * inertial here they should not be corrected for in an external filter processing the inertial
	 * output (which would lead to a double correction).
	 *
	 * @param time The time at which \p errors should be valid.
	 * @param errors An estimate of the inertial sensor's errors.
	 */
	void (*correct_sensor_errors)(struct PntosStandardInertialMechanization* self,
	                              AspnTypeTimestamp time,
	                              PntosStandardInertialErrors* errors);

	/**
	 * @param time Time at which inertial errors should be valid.
	 *
	 * @return Inertial errors at \p time if \p time is in the valid range
	 * (PntosCommonInertial.is_time_in_range can be used to check \p time before calling this
	 * method), NULL otherwise.
	 */
	PntosStandardInertialErrors* PNTOS_NULLABLE (*request_sensor_errors)(
	    struct PntosStandardInertialMechanization* self, AspnTypeTimestamp time);

} PntosStandardInertialMechanization;

/**
 * An implementation of an inertial plugin. This plugin generates PntosCommonInertial instances
 * which may be used to generate INS solutions from raw IMU data.
 *
 * **UNSTABLE**: This feature is unstable and is not yet considered part of the stable pntOS API.
 * Usage of this feature is highly discouraged in non-experimental code, and its definition may
 * change at any time.
 */
typedef struct PntosInertialPlugin {

	PntosCommonPlugin common;

	/**
	 * Return if the plugin supports a given type of inertial. See #PntosInertialType.
	 */
	bool (*is_inertial_type_supported)(struct PntosInertialPlugin* self, PntosInertialType type);

	/**
	 * Create an instance of #PntosCommonInertial.
	 *
	 * @param type Specifies the type of inertial that the returned value will support. For example,
	 * if the user passes in #PNTOS_STANDARD_INERTIAL_MECHANIZATION, then the returned value will be
	 * castable to PntosStandardInertialMechanization. If \p type is unsupported by the plugin, then
	 * NULL will be returned. Please use #is_inertial_type_supported to check if the type is
	 * supported by the plugin.
	 * @param solution The initial solution (i.e. the alignment) to mechanize from.
	 * @param config_group An optional parameter which can be used to specify which group in the
	 * config should be used to initialize the new inertial. This allows for multiple inertial
	 * instances to exist with unique settings.
	 *
	 * @return A new inertial object. Returns NULL if \p type is unsupported, \p solution is
	 * invalid, or \p config_group is invalid. #is_inertial_type_supported can be called to verify
	 * \p type before calling this method.
	 */
	PntosCommonInertial* PNTOS_NULLABLE (*new_inertial)(struct PntosInertialPlugin* self,
	                                                    PntosInertialType type,
	                                                    PntosMessage* solution,
	                                                    char* PNTOS_NULLABLE config_group);

} PntosInertialPlugin;

#ifdef __cplusplus
}
#endif

PNTOS_ASSUME_NONNULL_END
